### PR TITLE
Don't count reserved partitions (gpt) when checking if any exist

### LINKED ISSUE #144: PartitionDisk doesn't work with GPT volumes
**What happened**: https://github.com/kubernetes-csi/csi-proxy/pull/128#issuecomment-852384290 (default to GPT instead of MBR) breaks PartitionDisk https://github.com/kubernetes-csi/csi-proxy/blob/a0b516eea0fc01a44f4746bc27438d335c95a589/internal/server/disk/server.go#L79 because PartitionDisk naively checks if any partition exists and erroneously detects the GPT 16MB reserved partition as one such partition. Result is that the UseMaximumSize partition doesn't get created and ListVolumeondisk unexpectedly returns one entry with empty string.

```
I0601 19:05:14.144201    5564 server.go:123] calling ListDiskIDs
I0601 19:05:16.365505    5564 server.go:122] calling PathExists with path "c:\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-ece81bd9-b1ed-4830-98ea-bf27958ef4bd\\globalmount"
I0601 19:05:16.366181    5564 server.go:238] calling GetVolumeFromMount with request &{Mount:c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ece81bd9-b1ed-4830-98ea-bf27958ef4bd\globalmount}
E0601 19:05:16.694188    5564 server.go:251] failed GetVolumeFromMount error getting the volume for the mount c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ece81bd9-b1ed-4830-98ea-bf27958ef4bd\globalmount, internal error error getting volume from mount. cmd: (Get-Item -Path c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ece81bd9-b1ed-4830-98ea-bf27958ef4bd\globalmount).Target, output: , error: <nil>
I0601 19:05:16.694464    5564 server.go:59] calling PartitionDisk with diskID "5"
I0601 19:05:18.923412    5564 server.go:69] Initializing disk 5
I0601 19:05:21.396159    5564 server.go:79] Checking if disk 5 is partitioned
I0601 19:05:23.877015    5564 server.go:93] Disk 5 already partitioned
I0601 19:05:26.353187    5564 server.go:109] calling IsVolumeFormatted with request: &{VolumeId:}
E0601 19:05:26.353187    5564 server.go:114] volume id empty
```

**What you expected to happen**: PartitionDisk works, volume gets found, formatted, and mounted, and my Pod using the volume runs.

**How to reproduce it**:

use latest csi-proxy with a csi driver

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wongma7**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:  see https://github.com/kubernetes-csi/csi-proxy/issues/144: with gpt being default, there is some 128MB reserved partition at beginning of disk. LIke
```
PartitionNumber  DriveLetter Offset                                        Size Type
---------------  ----------- ------                                        ---- ----
1                            1048576                                     128 MB Reserved
2                            135266304                                 19.87 GB Basic
```
Don't count it when checking if partition exists.

**Which issue(s) this PR fixes**:

Fixes #144

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
rebased (took a few tries xd)

**Comment by ddebroy** [comment]
Please update the comment at https://github.com/kubernetes-csi/csi-proxy/blob/2b7dc43193d792fccb453a67946230000892941d/internal/os/disk/api.go#L36 to state that reserved partition types are excluded.

Windows allows you to create Reserved partitions as well for GPT: https://docs.microsoft.com/en-us/powershell/module/storage/new-partition?view=windowsserver2019-ps. Instead of this change in the PR, how about listing partitions and skipping a single reserved partition if disk is GPT in https://github.com/kubernetes-csi/csi-proxy/blob/2b7dc43193d792fccb453a67946230000892941d/internal/server/disk/server.go#L70

**Comment by wongma7** [comment]
What about making it just check for Basic partitions? (Type -eq Basic). since this is an internal function only used by `PartitionDisk` (which is part of the API) to check whether `CreatePartition` needs to be called, and CreatePartition always creates a Basic partition, I think it is best to narrow the scope to just Basic

**Comment by wongma7** [comment]
> What about making it just check for Basic partitions?

I just pushed a change for what this looks like
```
52    6156 server.go:113] Request: ListDiskIDs
I0603 20:28:37.491552    6156 api.go:69] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c (Get-Disk | Select Path, SerialNumber) | ConvertTo-Json"
I0603 20:28:40.172585    6156 server.go:122] calling PathExists with path "c:\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\globalmount"
I0603 20:28:40.173288    6156 server.go:274] GetVolumeIDFromTargetPath: Request: &{TargetPath:c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\globalmount}
I0603 20:28:40.176496    6156 api.go:51] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c (Get-Item -Path c:\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\globalmount).Target"
E0603 20:28:40.552050    6156 server.go:283] failed GetVolumeIDFromTargetPath: error getting the volume for the mount c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\globalmount, internal error error getting volume from mount. cmd: (Get-Item -Path c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\globalmount).Target, output: , error: <nil>
I0603 20:28:40.560078    6156 server.go:49] Request: PartitionDisk with diskNumber=5
I0603 20:28:40.563608    6156 api.go:69] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c Get-Disk -Number 5 | Where partitionstyle -eq 'raw'"
I0603 20:28:42.931157    6156 server.go:59] Initializing disk 5
I0603 20:28:42.933984    6156 api.go:69] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c Initialize-Disk -Number 5 -PartitionStyle GPT"
I0603 20:28:45.275301    6156 server.go:69] Checking if disk 5 has basic partitions
I0603 20:28:45.277312    6156 api.go:69] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c Get-Partition | Where DiskNumber -eq 5 | Where Type -eq Basic"
I0603 20:28:47.533401    6156 server.go:76] Creating basic partition on disk 5
I0603 20:28:47.536044    6156 api.go:69] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c New-Partition -DiskNumber 5 -UseMaximumSize"
I0603 20:28:49.993549    6156 server.go:25] ListVolumesOnDisk: Request: &{DiskNumber:5 PartitionNumber:0}
I0603 20:28:50.008933    6156 api.go:51] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c (Get-Disk -Number 5 | Get-Partition | Get-Volume).UniqueId"
I0603 20:28:52.604848    6156 server.go:97] IsVolumeFormatted: Request: &{VolumeId:\\?\Volume{0c64d232-5bcd-4cff-b9c3-d0e96a34f515}\}
I0603 20:28:52.607428    6156 api.go:51] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c (Get-Volume -UniqueId \"\\\\?\\Volume{0c64d232-5bcd-4cff-b9c3-d0e96a34f515}\\\" -ErrorAction Stop).FileSystemType"
I0603 20:28:54.944565    6156 server.go:116] FormatVolume: Request: &{VolumeId:\\?\Volume{0c64d232-5bcd-4cff-b9c3-d0e96a34f515}\}
I0603 20:28:54.947178    6156 api.go:51] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c Get-Volume -UniqueId \"\\\\?\\Volume{0c64d232-5bcd-4cff-b9c3-d0e96a34f515}\\\" | Format-Volume -FileSystem ntfs -Confirm:$false"
I0603 20:29:00.160646    6156 server.go:39] MountVolume: Request: &{VolumeId:\\?\Volume{0c64d232-5bcd-4cff-b9c3-d0e96a34f515}\ TargetPath:c:\var\lib\kubelet\plugins\kubernetes.io\csi\pv\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\globalmount}
I0603 20:29:00.161292    6156 api.go:51] Executing command: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe /c Get-Volume -UniqueId \"\\\\?\\Volume{0c64d232-5bcd-4cff-b9c3-d0e96a34f515}\\\" | Get-Partition | Add-PartitionAccessPath -AccessPath c:\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\globalmount"
I0603 20:29:03.286442    6156 server.go:122] calling PathExists with path "c:\\var\\lib\\kubelet\\pods\\ef469fdf-6cab-4535-8cd0-23d911a08e0d\\volumes\\kubernetes.io~csi\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\mount"
I0603 20:29:03.287104    6156 server.go:172] calling Rmdir with path "c:\\var\\lib\\kubelet\\pods\\ef469fdf-6cab-4535-8cd0-23d911a08e0d\\volumes\\kubernetes.io~csi\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\mount"
I0603 20:29:03.287890    6156 server.go:193] calling LinkPath with targetPath "c:\\var\\lib\\kubelet\\pods\\ef469fdf-6cab-4535-8cd0-23d911a08e0d\\volumes\\kubernetes.io~csi\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\mount" sourcePath "c:\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\pv\\pvc-ab6391a9-9b7d-4741-9c51-d304d90bf58c\\globalmount"
```

File: internal/os/disk/api.go [hunk 1]
```diff
@@ -157,8 +157,8 @@ func (DiskAPI) InitializeDisk(diskNumber uint32) error {
 	return nil
 }
 
-func (DiskAPI) PartitionsExist(diskNumber uint32) (bool, error) {
-	cmd := fmt.Sprintf("Get-Partition | Where DiskNumber -eq %d", diskNumber)
+func (DiskAPI) BasicPartitionsExist(diskNumber uint32) (bool, error) {
+	cmd := fmt.Sprintf("Get-Partition | Where DiskNumber -eq %d | Where Type -eq Basic", diskNumber)
```
Comment (andyzhangx) [inline internal/os/disk/api.go:161]: @wongma7 if it's a MBR disk, `Type` would be `IFS`, so this change would break existing MBR disk
