### PR TITLE
Failing closed after maximum retry is achieved to avoid inf recursion

### LINKED ISSUE #193: High cpu usage of powershell processes triggered by csi-proxy
**What happened**: 
We are doing some performance tests for vsphere-csi-driver (https://github.com/kubernetes-sigs/vsphere-csi-driver) on k8s cluster with 20 windows worker nodes. Each node has 4 CPUs and 16GB of memory. k8s version is 1.22.3, windows version is Windows Server 2019. the vsphere csi node plugin uses csi-proxy for privileged operations on host devices. The test repeatedly issues CreatePod followed by DeletePod. Each Pod just starts one container with image "mcr.microsoft.com/oss/kubernetes/pause:1.4.1", and mounts one persistent volume.
 
During the test we observed high cpu usage on the windows worker nodes, and most of the cpu usage came from the powershell processes triggered by csi-proxy. With 1.4 Pod creations per second, the average cpu usage on each node is about 75% of the total cpu capacity, the CPU cost of powershell processes triggered by csi-proxy is about 45% of the total CPU capacity; With 2.4 Pod creations per second, the cpu usage on each node reached almost 100%, and the CPU cost of powershell processes triggered by csi-proxy is about 68%. As a comparison, for vsphere-csi-driver on Linux nodes, with 3 Pod creations per second the cpu usage on each node is constantly below 10%. 

**What you expected to happen**:
Reduce the cpu cost of csi-proxy.

**How to reproduce it**:
deploy vsphere-csi-driver on k8s cluster with windows nodes, and create Pod with PV mount, then delete Pod. 

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: vsphere CSI 2.5
- Kubernetes version (use `kubectl version`): 1.22.3
- OS (e.g. from /etc/os-release): Windows Server 2019
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by knabben**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
/kind bug

**What this PR does / why we need it**:
Adding a maximum retry for the CSI to find the volume target from a mountpath.

**Which issue(s) this PR fixes**:

Fixes #193 

**Special notes for your reviewer**:
Tracking the recursion call trace here:
https://github.com/kubernetes-csi/csi-proxy/issues/193#issuecomment-2059665463

**Does this PR introduce a user-facing change?**:

```release-note
Maximum retry (3) when for the getTarget method iterate and find the correct volume of the mount path. 
```

### CODE REVIEW

File: pkg/os/volume/api.go [hunk 1]
```diff
@@ -277,22 +281,23 @@ func (VolumeAPI) GetVolumeIDFromTargetPath(mount string) (string, error) {
...
 }
 
-func getTarget(mount string) (string, error) {
+func getTarget(mount string, retry int) (string, error) {
 	cmd := `(Get-Item -Path $Env:mountpath).Target`
 	cmdEnv := fmt.Sprintf("mountpath=%s", mount)
 	out, err := utils.RunPowershellCmd(cmd, cmdEnv)
-	if err != nil || len(out) == 0 {
-		return "", fmt.Errorf("error getting volume from mount. cmd: %s, output: %s, error: %v", cmd, string(out), err)
+	if err != nil || len(out) == 0 || retry >= MaxGetTargetRetry {
```
Comment (mauriciopoppe) [inline pkg/os/volume/api.go:288]: We can have many ifs, that way we know which was the actual reason e.g.

```go
if err != nil {
   // error message
}

if len(out) == 0 {
   // no length error message
}

if retry == 256 {
   // max recursion reached error message
}
```

File: pkg/os/volume/api_test.go [hunk 2]
```diff
@@ -0,0 +1,32 @@
+package volume
+
+import (
+	"github.com/stretchr/testify/assert"
+	"testing"
+)
+
+func TestGetTarget(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mauriciopoppe) [reply pkg/os/volume/api_test.go:8]: Agreed, it'd be hard to setup a scenario with symlinks so that `(Get-Item -Path $Env:mountpath).Target` works though.

File: pkg/os/volume/api.go [hunk 3]
```diff
@@ -277,22 +281,23 @@ func (VolumeAPI) GetVolumeIDFromTargetPath(mount string) (string, error) {
...
+		return "", fmt.Errorf("error getting volume from mount. cmd: %s, output: %s, error: %v, :retry %d", cmd, string(out), err, retry)
 	}
+
```
Comment (mauriciopoppe) [inline pkg/os/volume/api.go:291]: For debugging purposes of https://github.com/kubernetes-csi/csi-proxy/issues/193#issuecomment-2059665463 maybe you could add

```
klog.V(8).Infof("retry: %d, volumeString: %s", retry, volumeString)
```

And start the server with very high verbosity

**Comment by mauriciopoppe** [comment]
I believe CI is failing because the kubernetes startup script on GCE instances is not working for Windows, cc @anishshah

**Comment by AnishShah** [comment]
I had filed kubernetes/kubernetes#124047 to track sig-windows-gce test job failures.

**Comment by knabben** [comment]
@mauriciopoppe any news in the gcp windows testing?

**Comment by mauriciopoppe** [comment]
Thanks for following up, our CI infra is up and running but a presubmit within Github Actions failed with tests unrelated with this change:

```
=== RUN   TestSmbAPIGroup/v1alpha1SmbTests
    smb_v1alpha1_test.go:30: TestSmbAPIGroup setupUser failed: exit status 1, output: "ConvertTo-SecureString : The 'ConvertTo-SecureString' command was found in the module 'Microsoft.PowerShell.Security', \r\nbut the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'.\r\nAt line:1 char:10\r\n+ $PWord = ConvertTo-SecureString $Env:password -AsPlainText -Force;New ...\r\n+          ~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (ConvertTo-SecureString:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule\r\n \r\nNew-LocalUser : Cannot validate argument on parameter 'Password'. The argument is null. Provide a valid value for the \r\nargument, and then try running the command again.\r\nAt line:1 char:132\r\n+ ... w-Localuser -name $Env:username -accountneverexpires***                                                                    ~~~~~~\r\n    + CategoryInfo          : InvalidData: (:) [New-LocalUser], ParameterBindingValidationException\r\n    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.NewLocalUserCommand\r\n \r\n"
```

The failure above (only CI setup in Github actions) would need to be fixed in another PR and then we can retrigger presubmit tests in this PR to finally get it merged.

**Comment by mauriciopoppe** [comment]
Closing and reopening to trigger presubmit checks.

**Comment by mauriciopoppe** [comment]
/hold

Would it be possible to squash the commits? I think we should be able to cherrypick the commit to the library branch for CSI Proxy v2 after that.
