### PR TITLE
Send arrays to ConvertTo-Json in the internal disk implementation

### LINKED ISSUE #153: CSI-Proxy fails to return the disks through disk.ListDiskIDs and disk.ListDiskLocations in a VM with only one disk
**What happened**:

In a VM with only a single disk (like when it's a new VM) the integration tests fail while trying to get the list of disks, this command:

```
(Get-Disk | Select Path, SerialNumber) | ConvertTo-Json
```

Will return an object if there's only one disk but an array of objects if there are many disks, the go code is always unmarshalling an array so if it only has one disk it fails during unmarshalling (silently), the result is that this method returns no disks when there's one disk.

https://github.com/kubernetes-csi/csi-proxy/blob/e7c1df0223edc2d12e6b1e42d6251686018ef57e/internal/os/disk/api.go#L286-L305

### PR DESCRIPTION
**Pull request by mauriciopoppe**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind bug

**What this PR does / why we need it**:

Context #153, we're using `ConvertTo-Json @(...)` instead of pipes

**Which issue(s) this PR fixes**:

Fixes #153 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/hold
/cc @jingxu97 @ddebroy 

We should merge #152 first

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
I've also checked the other places in `volume` that were using `| ConvertTo-Json` and they don't use array, they use maps so I think we're ok

/unhold

File: pkg/os/disk/api.go [hunk 1]
```diff
@@ -93,8 +93,8 @@ func (DiskAPI) ListDiskLocations() (map[uint32]shared.DiskLocation, error) {
 
 	m := make(map[uint32]shared.DiskLocation)
 	for _, v := range getDisk {
-		str := v["location"].(string)
-		num := v["number"].(float64)
+		str := v["Location"].(string)
```
Comment (jingxu97) [inline pkg/os/disk/api.go:96]: why change location --> Location?

Comment (mauriciopoppe) [reply pkg/os/disk/api.go:96]: this change is actually not needed and I can revert it back, it's because I also changed this line above:

```
cmd := fmt.Sprintf("ConvertTo-Json @(Get-Disk | select Number, Location)")
```

Comment (mauriciopoppe) [reply pkg/os/disk/api.go:96]: I think I can skip making this change, I already run the integration tests on #155 and they're passing with the v1 API too

**Comment by jingxu97** [comment]
/lgtm
approve
